/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo.login;

import java.util.*;

public class Login{
    private static final Map<String,String> logins = new LinkedHashMap<>();

    static void cadastrarLogin(String login, String senha){
        logins.put(login,senha);
    }

    static void removeLogin(String login){
        logins.remove(login);
    }

    static void listarLogin(){
        logins.forEach((login,senha) -> {System.out.println("LOGIN: " + login + " | " + "SENHA: " + senha);});
    }

    static boolean autenticarLogin(String login, String senha){
        return logins.entrySet().contains(Map.entry(login, senha));
    }

    public static void main(String[] args) {

        cadastrarLogin("João","12345678");
        cadastrarLogin("ShaolinMatadorDePorcos2.0","EuSouSuperShaolin98763");
        cadastrarLogin("CorDeBurroQuandoFOge","Cambalaxo");
        cadastrarLogin("CagueiNasCalças", "ngfjoirwbnpoguj982758t");
        cadastrarLogin("JalinRabey", "VoulinRabar890213");
        cadastrarLogin("PacoteOffice","BillGades01110100");

        listarLogin();

        removeLogin("CorDeBurroQuandoFOge");
        removeLogin("João");

        System.out.println();

        listarLogin();

        System.out.println();

        if(autenticarLogin("JalinRabey","VoulinRabar890213")){
            System.out.println("O usuário existe");
        }
        else{System.out.println("O usuário não existe");}


    }
}
