/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo.login;

import java.util.*;

public class Login{
    private static final Set<Usuario> usuarios = new LinkedHashSet<>();

    static void cadastrarLogin(String login, String senha){
        usuarios.add(new Usuario(login,senha));
    }

    static void removeLogin(String login){
        usuarios.removeIf(usuario -> usuario.getLogin().equals(login));
    }

    static void listarLogin(){
        usuarios.forEach((usuario) -> {System.out.println("LOGIN: " + usuario.getLogin() + " | " + "SENHA: " + usuario.getSenha());});
    }

    static boolean autenticarLogin(String login, String senha){
        return usuarios.contains(new Usuario(login,senha));
    }

    public static void main(String[] args) {

        cadastrarLogin("João","12345678");
        cadastrarLogin("ShaolinMatadorDePorcos2.0","EuSouSuperShaolin98763");
        cadastrarLogin("CorDeBurroQuandoFOge","Cambalaxo");
        cadastrarLogin("CagueiNasCalças", "ngfjoirwbnpoguj982758t");
        cadastrarLogin("JalinRabey", "VoulinRabar890213");
        cadastrarLogin("PacoteOffice","BillGades01110100");

        listarLogin();

        removeLogin("CorDeBurroQuandoFOge");
        removeLogin("João");

        System.out.println();

        listarLogin();

        System.out.println();

        if(autenticarLogin("JalinRabey","VoulinRabar890213")){
            System.out.println("O usuário existe");
        }
        else{System.out.println("O usuário não existe");} //


    }
}
